# This file was generated by GoReleaser. DO NOT EDIT.
cask "seamless" do
  version "0.5.4"

  on_macos do
    on_arm do
      sha256 "6d45022bf8459e2d572fa763f071a6fdb6259265653e7c88555227f460192c82"
      url "https://github.com/0spoon/seamless/releases/download/v#{version}/seamless_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e2c63750dbdba5979495894d556b345e80b7a92922b46464b3c53f7b8d072785"
      url "https://github.com/0spoon/seamless/releases/download/v#{version}/seamless_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "fed6217cc53ea7e01a850eb0340a67cea69844475a951191adf630c0b69327f6"
      url "https://github.com/0spoon/seamless/releases/download/v#{version}/seamless_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ded3d53f76f4b35dc00470db7ed008818a79dcf984688ddead6f7ee9762fa3a6"
      url "https://github.com/0spoon/seamless/releases/download/v#{version}/seamless_#{version}_linux_amd64.tar.gz"
    end
  end

  name "seamless"
  desc "Local-first shared memory and task coordination for AI coding agents. One Go binary, MCP server, markdown files you own. Hooks for Claude Code and Codex CLI (and their desktop apps)."
  homepage "https://thereisnospoon.org"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "seamlessd"
  binary "seam"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/seamlessd"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/seam"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Connect your agent clients (hooks, MCP registration, skills):
      seamlessd install-hooks
    Then start the daemon (it bootstraps config + key on first run):
      seamlessd serve
    Quickstart: https://thereisnospoon.org/docs/quickstart/
  EOS
end
